/**
 * Roman Urdu for every phrase on screen, keyed by its English.
 *
 * Written for owners who read little: the everyday words of the mandi
 * (sale, gahak, beopari, khata, udhaar, nakad, kharcha, laagat, munafa,
 * nuqsan, lene hain / dene hain, baqi), short sentences, and no formal Urdu.
 * Keep the same words for the same things everywhere.
 *
 * `npm run check:i18n` lists any phrase missing here.
 */
export const UR: Record<string, string> = {
  // ------------------------------------------------------------ the frame --
  Home: 'Home',
  Challans: 'Challan',
  Sales: 'Sales',
  Ledgers: 'Khatay',
  'Cash & bank': 'Nakad aur bank',
  Expenses: 'Kharchay',
  Reports: 'Reports',
  Settings: 'Settings',
  More: 'Aur',
  Language: 'Zubaan',
  'Demo · records stay in this browser': 'Demo · hisaab sirf is browser mein',
  'Sign out': 'Logout karein',

  // ------------------------------------------------------------- sign in --
  'Challans, sales, ledgers and cash, in one place.': 'Challan, sale, khatay aur nakad, sab ek jagah.',
  Email: 'Email',
  Password: 'Password',
  'Signing in…': 'Login ho raha hai…',
  'Sign in': 'Login karein',
  "Ask the owner for the business's login.": 'Login ke liye malik se poochein.',

  // -------------------------------------------------------- common words --
  Cash: 'Nakad',
  Bank: 'Bank',
  Today: 'Aaj',
  Yesterday: 'Kal',
  Profit: 'Munafa',
  Loss: 'Nuqsan',
  'Profit so far': 'Ab tak munafa',
  'Loss so far': 'Ab tak nuqsan',
  Customer: 'Gahak',
  Supplier: 'Beopari',
  Customers: 'Gahak',
  Suppliers: 'Beopari',
  customer: 'gahak',
  customers: 'gahak',
  supplier: 'beopari',
  suppliers: 'beopari',
  animal: 'janwar',
  animals: 'janwar',
  'damaged animal': 'zakhmi janwar',
  'damaged animals': 'zakhmi janwar',
  Animals: 'Janwar',
  'Walk-in customer': 'Bina khata gahak',
  'Challan #{n}': 'Challan #{n}',
  'Sale #{n}': 'Sale #{n}',
  Date: 'Tareekh',
  Notes: 'Note',
  'Optional.': 'Zaroori nahi.',
  Amount: 'Raqam',
  '{n} thousand': '{n} hazar',
  All: 'Sab',
  Nothing: 'Kuch nahi',
  'Nothing yet': 'Abhi kuch nahi',
  None: 'Koi nahi',
  Paid: 'Poora mila',
  Damaged: 'Zakhmi',
  damaged: 'zakhmi',
  'sold out': 'sab bik gaye',
  'Sold out': 'Sab bik gaye',
  'On credit': 'Udhaar',
  '{amount} on credit': '{amount} udhaar',
  '{n} left': '{n} baqi',
  'cost {amount}': 'laagat {amount}',
  cost: 'laagat',
  'It may have been deleted.': 'Shayad mita diya gaya hai.',
  'Not found': 'Nahi mila',

  // ------------------------------------------------------------- buttons --
  Save: 'Save karein',
  'Saving…': 'Save ho raha hai…',
  'Save changes': 'Tabdeeli save karein',
  Saved: 'Save ho gaya',
  Cancel: 'Wapas',
  Delete: 'Mitayein',
  Edit: 'Badlein',
  Close: 'Band karein',
  'Working…': 'Ho raha hai…',
  'Loading…': 'Load ho raha hai…',
  'Try again': 'Dobara koshish karein',
  'Remove this line': 'Ye line hatayein',

  // ---------------------------------------------------------------- home --
  'New sale': 'Nayi sale',
  'New challan': 'Naya challan',
  Death: 'Janwar mara',
  Payment: 'Lein dein',
  Expense: 'Kharcha',
  'Cash in hand': 'Haath mein nakad',
  'Customers owe you': 'Gahakon se lene hain',
  'You owe suppliers': 'Beopariyon ko dene hain',
  'Animals in stock': 'Baqi janwar',
  'Cost {amount}': 'Laagat {amount}',
  'Sales {amount}': 'Sales {amount}',
  'Nothing yet this month': 'Is mahine abhi kuch nahi',
  'All challans': 'Sab challan',
  'No animals in stock': 'Koi janwar baqi nahi',
  'Record a challan when you buy a lot of animals.': 'Jab janwar khareedein to challan likhein.',
  '{animals} left': '{animals} baqi',
  'Latest sales': 'Haal ki sales',
  'All sales': 'Sab sales',
  'No sales yet': 'Abhi koi sale nahi',

  // ------------------------------------------------------------ challans --
  '{open} with animals in stock · {sold} sold out': '{open} challan mein janwar baqi · {sold} challan bik gaye',
  'Which challans': 'Kaun se challan',
  'In stock': 'Janwar baqi',
  'No challan is sold out yet': 'Abhi kisi challan ke sab janwar nahi bike',
  'No challans here': 'Yahan koi challan nahi',
  'Record your first purchase with New challan.': 'Pehli khareed "Naya challan" se likhein.',
  'Challan not found': 'Challan nahi mila',
  'bought {date}': '{date} ko khareeda',
  Sell: 'Bechein',
  'How this is worked out': 'Hisaab kaise bana',
  'Challan details': 'Challan mein kya hai',
  'Fully paid': 'Pura ada',
  bought: 'khareede',
  sold: 'bik gaye',
  died: 'mare',
  left: 'baqi',
  sale: 'sale',
  sales: 'sales',
  expense: 'kharcha',
  expenses: 'kharchay',
  'Sold for': 'Sale',
  '{n} sold': '{n} bik gaye',
  'Final result': 'Akhri hisaab',
  'Result so far': 'Ab tak ka hisaab',
  'Final: every animal is sold or dead': 'Mukammal: sab janwar bik gaye ya mar gaye',
  'Cost of the {animals} sold or dead': 'Bikay ya maray {animals} ki laagat',
  'Expenses on this challan': 'Is challan ke kharchay',
  'In stock: {animals}, which cost {amount}. That cost counts once they are sold or die.':
    'Baqi: {animals}, laagat {amount}. Ye laagat tab ginti hai jab ye bikein ya marein.',
  '{n} bought': '{n} khareede',
  '{n} sold ({damaged} damaged)': '{n} bikay ({damaged} zakhmi)',
  '{n} died': '{n} mare',
  '{amount} each': 'aik ki laagat {amount}',
  '{sold} sold, {died} died, {left} left': '{sold} bikay, {died} mare, {left} baqi',
  '{n} died (what they cost)': '{n} mare (in ki laagat)',
  '{n} damaged, sold below cost by': '{n} zakhmi, laagat se itne kam mein bikay',
  'Already counted in the profit above.': 'Ye upar ke hisaab mein shamil hai.',
  'Payment to the supplier': 'Beopari ko paisay',
  'Paid at purchase ({account})': 'Khareed ke waqt diye ({account})',
  'Left on credit': 'Udhaar baqi',
  "The credit is on the supplier's ledger.": 'Udhaar beopari ke khate mein hai.',
  "Open {name}'s ledger": '{name} ka khata kholein',
  'Sales from this challan ({n})': 'Is challan ki sales ({n})',
  'Nothing sold yet': 'Abhi kuch nahi bika',
  Deaths: 'Mare hue janwar',
  'No expenses linked': 'Koi kharcha nahi likha',
  'Add transport, fodder and the like with Expense above.': 'Gari ka kiraya, chara waghera upar "Kharcha" se likhein.',
  'Delete challan #{n}?': 'Challan #{n} mitayein?',
  'Delete this challan': 'Ye challan mitayein',
  'It has no sales, deaths or expenses, so nothing else changes.':
    'Is ki koi sale, maut ya kharcha nahi, is liye aur kuch nahi badlega.',

  // -------------------------------------------------------- challan form --
  'Edit challan #{n}': 'Challan #{n} badlein',
  'One bulk purchase of animals.': 'Ek saath khareede gaye janwar.',
  'Date bought': 'Khareed ki tareekh',
  'Kind of animal': 'Kaun sa janwar',
  'Goat, sheep, cow…': 'Bakra, dumba, gaye…',
  'How many': 'Kitne',
  'Price each': 'Aik ki qeemat',
  'Total cost': 'Kul laagat',
  "{n} already sold or dead, so this line stays and its count can't go below {n}.":
    '{n} bik chuke ya mar chuke, is liye ye line rahegi aur ginti {n} se kam nahi ho sakti.',
  'Add another kind of animal': 'Doosra janwar shamil karein',
  'Challan total': 'Challan ka kul',
  'Paid now': 'Abhi diye',
  'Paid in full': 'Poore paisay',
  'Paid from': 'Paisay kahan se diye',
  "{amount} stays on credit, on the supplier's ledger.": '{amount} udhaar rahega, beopari ke khate mein.',
  'Nothing left on credit.': 'Koi udhaar nahi.',
  'Optional. A paper challan number, the truck, anything worth keeping.':
    'Zaroori nahi. Kaghaz wale challan ka number, gari ka number, ya koi aur baat.',
  'Save challan': 'Challan save karein',

  // --------------------------------------------------------------- sales --
  'This month: {amount} from {animals}': 'Is mahine: {animals} se {amount}',
  'Which sales': 'Kaun si sales',
  'No sales match': 'Aisi koi sale nahi',
  'Record one with New sale.': '"Nayi sale" se likhein.',
  'Sale not found': 'Sale nahi mili',
  'Edit sale #{n}': 'Sale #{n} badlein',
  'Date sold': 'Sale ki tareekh',
  'Animals sold': 'Bikay janwar',
  'From which challan': 'Kis challan se',
  'Total price': 'Kul qeemat',
  'injured or sick, sold cheap': 'ya beemar, is liye sasta bika',
  'They cost {amount}': 'In ki laagat {amount}',
  'Add other animals': 'Aur janwar shamil karein',
  'Sale total': 'Sale ka kul',
  'A walk-in customer pays the full {amount} now. Pick a customer to sell on credit.':
    'Bina khata gahak poore {amount} abhi deta hai. Udhaar dena hai to gahak chunein.',
  'Received now': 'Abhi mile',
  'All on credit': 'Sab udhaar',
  'Received in': 'Paisay kahan aaye',
  "It goes on the customer's ledger.": 'Ye gahak ke khate mein jayega.',
  'On this sale': 'Is sale par',
  'Save sale': 'Sale save karein',
  'The {animals} go back into stock.': '{animals} wapas baqi mein aa jayenge.',
  "The {amount} credit comes off {name}'s ledger.": '{name} ke khate se {amount} udhaar hat jayega.',
  'The money comes out of the books.': 'Ye paisay hisaab se nikal jayenge.',
  'From challan #{n}': 'Challan #{n} se',
  'Received now ({account})': 'Abhi mile ({account})',
  'Cost of these animals {amount}': 'In janwaron ki laagat {amount}',
  "The credit is on the customer's ledger.": 'Udhaar gahak ke khate mein hai.',
  'Delete sale #{n}?': 'Sale #{n} mitayein?',
  'Delete this sale': 'Ye sale mitayein',

  // ------------------------------------------------------------- ledgers --
  'New customer': 'Naya gahak',
  'New supplier': 'Naya beopari',
  'Customers or suppliers': 'Gahak ya beopari',
  'Find a customer': 'Gahak dhoondein',
  'Find a supplier': 'Beopari dhoondein',
  'Nobody matches': 'Koi nahi mila',
  'No customers yet': 'Abhi koi gahak nahi',
  'No suppliers yet': 'Abhi koi beopari nahi',
  'They are added from a sale, or with New customer.': 'Gahak sale ke waqt ya "Naya gahak" se bante hain.',
  'They are added from a challan, or with New supplier.': 'Beopari challan ke waqt ya "Naya beopari" se bante hain.',
  Settled: 'Hisaab barabar',
  'Owes you': 'Lene hain',
  'Paid in advance': 'Advance diya hua',
  'You owe': 'Dene hain',
  'You paid in advance': 'Aap ne advance diya',
  'Payment received': 'Paisay mile',
  'Payment made': 'Paisay diye',
  'Ledger, newest first': 'Khata (naya sab se upar)',
  'Balance after each': 'Har line ke baad baqaya',
  'bill {amount}': 'bill {amount}',
  'owed {amount}': 'baqaya {amount}',
  'paid {amount}': 'ada {amount}',
  Call: 'Call karein',
  WhatsApp: 'WhatsApp',
  // The message WhatsApp opens with, written to the customer or supplier.
  'Hello {name},': 'Assalam-o-Alaikum {name},',
  'Your account with {business}, as of {date}:': '{business} ke saath aap ka hisaab, {date} tak:',
  'Your account as of {date}:': 'Aap ka hisaab, {date} tak:',
  'Your whole account as of {date}:': '{date} tak aap ka pura hisaab:',
  'You owe us {amount}.': 'Aap ne humein {amount} dene hain.',
  'We owe you {amount}.': 'Hum ne aap ko {amount} dene hain.',
  'We hold {amount} of yours in advance.': 'Aap ke {amount} humare paas advance jama hain.',
  'You hold {amount} of ours in advance.': 'Humare {amount} aap ke paas advance jama hain.',
  'Your account is settled. Nothing is due.': 'Aap ka hisaab barabar hai. Koi baqaya nahi.',
  'Thank you.': 'Shukriya.',
  'Opening balance': 'Purana hisaab',
  'Owed before the app': 'App se pehle ka baqaya',

  // ------------------------------------------------------- cash and bank --
  'Payment or transfer': 'Paisay ka lein dein',
  'Which book': 'Kaun sa hisaab',
  'Combined balance': 'Kul paisay',
  'Cash in bank': 'Bank mein paisay',
  'Balance sheet': 'Balance sheet',
  Details: 'Kya hua',
  'Money in': 'Paisay aaye',
  'Money out': 'Paisay gaye',
  Balance: 'Baqaya',
  'Nothing in this period': 'In dinon mein koi lein dein nahi',
  'Earlier balance': 'Pichla baqaya',
  'Before {date}': '{date} se pehle',
  Period: 'Muddat',
  Monthly: 'Mahana',
  Quarterly: 'Teen mahine',
  'Bi-annually': 'Chhe mahine',
  Annually: 'Saalana',
  'Custom date range': 'Apni tareekhein',
  From: 'Kab se',
  To: 'Kab tak',
  Earlier: 'Pichla',
  Later: 'Agla',
  'Show the list': 'List dikhayein',
  'Close the list': 'List band karein',
  'Which one': 'Kaun sa',
  'Balance {amount}': 'Baqaya {amount}',
  'Nothing in this book yet': 'Is hisaab mein abhi kuch nahi',
  'When you started using the app': 'Jab app shuru ki',
  'Received from customer': 'Gahak se paisay mile',
  'Paid to supplier': 'Beopari ko paisay diye',
  'Cash put in the bank': 'Nakad bank mein jama kiya',
  'Cash taken from the bank': 'Bank se nakad nikala',
  'Owner put money in': 'Malik ne paisay daale',
  'Owner took money out': 'Malik ne paisay nikale',

  // ------------------------------------------------------------ expenses --
  'This month: {amount}': 'Is mahine: {amount}',
  'No expenses yet': 'Abhi koi kharcha nahi',
  'Transport, fodder, rent, wages: anything the business pays for.':
    'Gari ka kiraya, chara, kiraya, tankhwah: karobar ka har kharcha.',
  General: 'Aam',
  Transport: 'Gari ka kiraya',
  Fodder: 'Chara',
  'Vet & medicine': 'Dawai aur doctor',
  Labour: 'Mazdoori',
  'Mandi fee': 'Mandi fees',
  Rent: 'Kiraya',
  Wages: 'Tankhwah',
  Electricity: 'Bijli',

  // ------------------------------------------------------------- animals --
  Goat: 'Bakra',
  Sheep: 'Dumba',
  Cow: 'Gaye',
  Bull: 'Bail',
  Buffalo: 'Bhains',
  Calf: 'Bachra',
  Camel: 'Oont',

  // -------------------------------------------------------------- report --
  "An animal's cost counts when it is sold or dies, so a big purchase doesn't show as a loss.":
    'Janwar ki laagat tab ginti hai jab wo bike ya mare. Is liye bari khareed nuqsan mein nahi dikhti.',
  'Nothing to report yet': 'Abhi koi hisaab nahi',
  '{animals} · {received} paid at sale, {credit} on credit': '{animals} · {received} nakad mile, {credit} udhaar',
  'Cost of the animals sold': 'Bikay janwaron ki laagat',
  'Animals that died ({n})': 'Mare hue janwar ({n})',
  'What they cost': 'In ki laagat',
  '{animals} sold {amount} below cost. That is already inside the figures above.':
    '{animals} laagat se {amount} kam mein bikay. Ye upar ke hisaab mein shamil hai.',
  'Bought {animals} for {amount} in this time. Their cost counts as they are sold.':
    'In dinon mein {animals} {amount} mein khareede. In ki laagat bikne par ginti hai.',

  // ------------------------------------------------------- app and offline --
  Online: 'Online',
  Offline: 'Offline',
  'No internet.': 'Internet nahi hai.',
  'Keep working: everything is saved on this phone.': 'Kaam jaari rakhein: sab kuch is phone par save ho raha hai.',
  'A new version of the app is ready.': 'App ka naya version tayyar hai.',
  Update: 'Update karein',
  'The app now opens without internet too.': 'Ab app internet ke baghair bhi khulegi.',
  'Sync with the server': 'Server ke saath sync',
  '{n} changes need you': '{n} tabdeeliyan dekhni hain',
  '1 change needs you': '1 tabdeeli dekhni hai',
  'Offline · 1 change waiting': 'Offline · 1 tabdeeli baqi',
  'Offline · {n} changes waiting': 'Offline · {n} tabdeeliyan baqi',
  'Sending…': 'Bhej rahe hain…',
  '1 change will be sent when it is back.': 'Internet aate hi 1 tabdeeli bhej di jayegi.',
  'Sending 1 change to the server…': '1 tabdeeli server ko bhej rahe hain…',
  '1 change could not be saved on the server.': '1 tabdeeli server par save nahi ho saki.',
  '1 change waiting to be sent': '1 tabdeeli bhejni baqi hai',
  '{n} changes waiting to be sent': '{n} tabdeeliyan bhejni baqi hain',
  '1 change has not reached the server yet. It stays on this phone and goes when you sign in again. Sign out?':
    '1 tabdeeli abhi server tak nahi pohnchi. Ye is phone par mehfooz rahegi aur dobara sign in karne par chali jayegi. Sign out karein?',
  'Everything is saved on the server': 'Sab kuch server par save hai',
  'Online · everything is saved': 'Online · sab save hai',
  'Sign in again to send changes': 'Tabdeeliyan bhejne ke liye dobara sign in karein',
  '{n} changes will be sent when it is back.': 'Internet aate hi {n} tabdeeliyan bhej di jayengi.',
  'Sending {n} changes to the server…': '{n} tabdeeliyan server ko bhej rahe hain…',
  '{n} changes could not be saved on the server.': '{n} tabdeeliyan server par save nahi ho sakin.',
  'Tap to see them.': 'Dekhne ke liye dabayein.',
  'Changes are waiting: sign in again to send them.': 'Tabdeeliyan ruki hui hain: bhejne ke liye dobara sign in karein.',
  'Last brought up to date {when}': 'Aakhri baar {when} update hua',
  'Not brought up to date yet': 'Abhi update nahi hua',
  'Sync now': 'Abhi sync karein',
  'Need you ({n})': 'Dekhni hain ({n})',
  'Waiting to be sent ({n})': 'Bhejni baqi ({n})',
  'Everything on this phone is on the server too.': 'Is phone ka sab kuch server par bhi hai.',
  'Every change is saved on this phone first, then sent to the server by itself whenever there is internet. Nothing is lost if the connection drops.':
    'Har tabdeeli pehle is phone par save hoti hai, phir internet milte hi khud server ko chali jati hai. Internet toot jaye to bhi kuch zaya nahi hota.',
  'This was changed on another phone too. Which copy should stay?': 'Ye doosre phone par bhi badla gaya hai. Kaun si copy rakhni hai?',
  'Keep mine': 'Meri wali rakhein',
  'Keep the other phone’s': 'Doosre phone wali rakhein',
  'Drop this change': 'Ye tabdeeli chhor dein',
  '{n} changes have not reached the server yet. They stay on this phone and go when you sign in again. Sign out?':
    '{n} tabdeeliyan abhi server tak nahi pohnchin. Ye is phone par mehfooz rahengi aur dobara sign in karne par chali jayengi. Sign out karein?',
  'No internet, and this phone has no copy of the books yet. Connect once to fetch them.':
    'Internet nahi hai, aur is phone par abhi hisaab ki copy nahi. Ek dafa internet se jor kar hisaab mangwa lein.',
  'Deleted: {what}': 'Mitaya: {what}',
  'just now': 'abhi abhi',
  '{n} min ago': '{n} minute pehle',
  '{n} hours ago': '{n} ghante pehle',
  'The app is installed': 'App install ho chuki hai',
  'Install the app': 'App install karein',
  'It opens from its own icon, even without internet.': 'Ye apne icon se khulti hai, internet ke baghair bhi.',
  'In Safari, tap the Share button, then “Add to Home Screen”.':
    'Safari mein Share ka button dabayein, phir “Add to Home Screen” chunein.',
  'Open the browser menu and choose “Install app” or “Add to Home screen”.':
    'Browser ka menu kholein aur “Install app” ya “Add to Home screen” chunein.',
  'It opens from its own icon like any app, and works without internet.':
    'Ye baqi apps ki tarah apne icon se khulegi, aur internet ke baghair bhi chalegi.',
  Install: 'Install karein',
  'The records on this phone are kept safe: the browser will not clear them.':
    'Is phone par hisaab mehfooz hai: browser ise nahi mitayega.',
  'The browser may clear records on this phone when it runs low on space. Installing the app helps keep them.':
    'Phone mein jagah kam ho to browser yahan ka hisaab mita sakta hai. App install karne se ye mehfooz rehta hai.',

  // ------------------------------------------------------------ settings --
  'Words on the screen. Each phone remembers its own choice.': 'Screen ki zubaan. Har phone apni pasand yaad rakhta hai.',
  'Business name': 'Karobar ka naam',
  'Money when you started': 'Shuru mein paisay',
  'What was in the cash box and the bank on the day you began using the app. Every sale, payment and expense since is added to these.':
    'Jis din app shuru ki, us din haath mein aur bank mein kitne paisay thay. Us ke baad ki har sale, lein dein aur kharcha in mein jorra jata hai.',
  'In the bank': 'Bank mein',
  'Demo records': 'Demo hisaab',
  'The demo keeps its records in this browser only. Start again with the sample books, or with empty ones to try entering your own.':
    'Demo ka hisaab sirf is browser mein rehta hai. Namoone ka hisaab dobara layein, ya khaali shuru kar ke apna likh kar dekhein.',
  'Load the sample again': 'Namoona dobara layein',
  'Start empty': 'Khaali shuru karein',
  'Start with empty books?': 'Khaali hisaab se shuru karein?',
  'Load the sample again?': 'Namoona dobara layein?',
  'Everything entered in this demo is cleared.': 'Is demo mein likha sab kuch mit jayega.',
  'Load sample': 'Namoona layein',
  'Signed in as': 'Login hai',

  // --------------------------------------------------------- small forms --
  'Edit customer': 'Gahak badlein',
  'Edit supplier': 'Beopari badlein',
  Name: 'Naam',
  Phone: 'Phone',
  'Already owed to you': 'Pehle se lene hain',
  'You already owed them': 'Pehle se dene hain',
  'Credit from before you started using the app. Leave empty if none.':
    'App shuru karne se pehle ka udhaar. Na ho to khaali chhor dein.',
  'Delete {name}?': '{name} ko mitayein?',
  'They have no records, so nothing else changes.': 'In ka koi hisaab nahi likha, is liye aur kuch nahi badlega.',
  'Edit death': 'Mara hua janwar badlein',
  'Record a death': 'Mara hua janwar likhein',
  'Which animals': 'Kaun se janwar',
  'How many died': 'Kitne mare',
  Cause: 'Wajah',
  "They cost {amount}. That comes off challan #{n}'s profit.": 'In ki laagat {amount} thi. Ye challan #{n} ke munafe se kategi.',
  'Delete this death?': 'Ye maut mitayein?',
  'The animals count as in stock again.': 'Janwar dobara baqi mein ginay jayenge.',
  'Edit payment': 'Lein dein badlein',
  'What happened': 'Kya hua',
  Into: 'Paisay kahan aaye',
  'Cash or bank': 'Nakad ya bank',
  'Delete this payment?': 'Ye lein dein mitayein?',
  'Balances and the cash book go back to how they were without it.':
    'Khatay aur nakad ka hisaab is ke baghair wala ho jayega.',
  'Nothing owed right now.': 'Abhi koi baqaya nahi.',
  'Owes you {amount}.': 'Is se {amount} lene hain.',
  'Has paid {amount} in advance.': 'Is ne {amount} advance diye hain.',
  'You owe {amount}.': 'Isay {amount} dene hain.',
  'You have paid {amount} in advance.': 'Aap ne isay {amount} advance diye hain.',
  'Edit expense': 'Kharcha badlein',
  'New expense': 'Naya kharcha',
  'What for': 'Kis cheez ka kharcha',
  'Transport, fodder, rent…': 'Gari ka kiraya, chara, kiraya…',
  'For which challan': 'Kis challan ka',
  "It comes off that challan's profit, and this month's.": 'Ye us challan ke munafe se bhi katega aur is mahine ke munafe se bhi.',
  "General costs come off the month's profit only.": 'Aam kharcha sirf mahine ke munafe se katta hai.',
  'Not for one challan (rent, wages…)': 'Kisi ek challan ka nahi (kiraya, tankhwah…)',
  'Delete this expense?': 'Ye kharcha mitayein?',

  // ------------------------------------------------------------- pickers --
  'Walk-in customer (pays in full)': 'Bina khata gahak (poore paisay abhi)',
  'Pick a customer…': 'Gahak chunein…',
  'Pick a customer': 'Gahak chunein',
  'Pick a supplier': 'Beopari chunein',
  'Search by name or phone': 'Naam ya phone se dhoondein',
  'Add “{name}” as a new customer': '“{name}” ko naya gahak banayein',
  'Add “{name}” as a new supplier': '“{name}” ko naya beopari banayein',
  'Search by animal, supplier or challan': 'Janwar ya beopari se dhoondein',
  'Search by supplier or challan': 'Beopari ya challan se dhoondein',
  'Nothing matches “{typed}”': '“{typed}” se kuch nahi mila',
  'No challans yet': 'Abhi koi challan nahi',
  'Pick a supplier…': 'Beopari chunein…',
  'Pick the animals…': 'Janwar chunein…',
  'Challan #{n} · {supplier} · {date}': 'Challan #{n} · {supplier} · {date}',
  '#{n} {animal} — {left} left · cost {each} each': '#{n} {animal} — {left} baqi · aik ki laagat {each}',

  // ------------------------------------------------------ mistakes caught --
  'Only {left} {animal} left.': 'Sirf {left} {animal} baqi hain.',
  'No {animal} left.': 'Koi {animal} baqi nahi.',
  'Only {left} {animal} left in challan #{n}.': 'Challan #{n} mein sirf {left} {animal} baqi hain.',
  'No {animal} left in challan #{n}.': 'Challan #{n} mein koi {animal} baqi nahi.',
  'Pick the supplier.': 'Beopari chunein.',
  'Enter the date.': 'Tareekh likhein.',
  'Add at least one kind of animal.': 'Kam az kam ek janwar likhein.',
  'Enter the kind of animal on every line.': 'Har line mein janwar ka naam likhein.',
  '{animal} is on two lines. Put each kind of animal on one line.':
    '{animal} do lines mein likha hai. Har janwar ek hi line mein likhein.',
  'Enter how many {animal} (a whole number).': 'Kitne {animal} hain, poori ginti likhein.',
  'Enter what the {animal} cost.': '{animal} ki laagat likhein.',
  'Enter how much was paid now, or 0.': 'Abhi kitne paisay diye, likhein. Kuch nahi diya to 0 likhein.',
  'Paid now is more than the challan total.': 'Abhi diye gaye paisay challan ke kul se zyada hain.',
  "{animal} already has sales or deaths, so it can't be taken off this challan.":
    '{animal} bik chuke ya mar chuke hain, is liye ye is challan se nahi hat sakte.',
  "{used} {animal} are already sold or dead, so the count can't go below {used}.":
    '{used} {animal} bik chuke ya mar chuke hain, is liye ginti {used} se kam nahi ho sakti.',
  'Pick the customer again.': 'Gahak dobara chunein.',
  'Add at least one animal.': 'Kam az kam ek janwar likhein.',
  'Pick which challan each animal came from.': 'Har janwar ka challan chunein.',
  'Enter how many animals (a whole number).': 'Kitne janwar hain, poori ginti likhein.',
  'Enter the price.': 'Qeemat likhein.',
  'Enter how much was received now, or 0.': 'Abhi kitne paisay mile, likhein. Kuch nahi mila to 0 likhein.',
  'Received now is more than the sale total.': 'Abhi mile paisay sale ke kul se zyada hain.',
  'A walk-in customer must pay in full. Pick a customer to sell on credit.':
    'Bina khata gahak ko poore paisay abhi dene hain. Udhaar dena hai to gahak chunein.',
  'Pick which animal died.': 'Kaun sa janwar mara, chunein.',
  'Enter how many died (a whole number).': 'Kitne mare, poori ginti likhein.',
  'Enter the amount.': 'Raqam likhein.',
  'Pick the customer.': 'Gahak chunein.',
  'Pick cash or bank.': 'Nakad ya bank chunein.',
  'Say what the money was spent on.': 'Paisay kis cheez par lage, likhein.',
  'Pick the challan again.': 'Challan dobara chunein.',
  'Enter the name.': 'Naam likhein.',
  'Enter the opening balance, or 0.': 'Purana baqaya likhein, ya 0 likhein.',
  'There is already a customer called {name}.': '{name} naam ka gahak pehle se mojood hai.',
  'There is already a supplier called {name}.': '{name} naam ka beopari pehle se mojood hai.',
  'This challan has sales. Delete those sales first.': 'Is challan ki sales hui hain. Pehle wo sales mitayein.',
  'This challan has deaths recorded. Delete those first.': 'Is challan mein mare hue janwar likhe hain. Pehle wo mitayein.',
  'This challan has expenses linked to it. Delete them or move them off this challan first.':
    'Is challan ke kharchay likhe hain. Pehle unhein mitayein ya kisi aur challan par daalein.',
  "This customer has sales, so they can't be deleted.": 'Is gahak ki sales likhi hain, is liye ye nahi mit sakta.',
  "This customer has payments, so they can't be deleted.": 'Is gahak ke lein dein likhe hain, is liye ye nahi mit sakta.',
  "This supplier has challans, so they can't be deleted.": 'Is beopari ke challan likhe hain, is liye ye nahi mit sakta.',
  "This supplier has payments, so they can't be deleted.": 'Is beopari ke lein dein likhe hain, is liye ye nahi mit sakta.',
  'Enter the business name.': 'Karobar ka naam likhein.',
  'Enter the opening balances, or 0.': 'Shuru ke paisay likhein, ya 0 likhein.',

  // ---------------------------------------------------- from the database --
  'The app is not connected to its database yet. See README.md.': 'App abhi database se nahi juri. README.md dekhein.',
  'You have been signed out. Please sign in again.': 'Aap logout ho gaye hain. Dobara login karein.',
  'That is already saved.': 'Ye pehle se save hai.',
  'Other records still use this, so it cannot be changed or deleted.':
    'Baqi hisaab is se jura hai, is liye ye badla ya mitaya nahi ja sakta.',
  "Can't reach the server. Check the internet connection and try again.":
    'Server se rabta nahi ho raha. Internet check karein aur dobara koshish karein.',
  'Something went wrong. Please try again.': 'Kuch ghalat ho gaya. Dobara koshish karein.',
  'Wrong email or password.': 'Email ya password ghalat hai.',
  'An animal you took off this challan already has sales or deaths. Put it back first.':
    'Jo janwar aap ne challan se hataya, wo bik chuka ya mar chuka hai. Pehle usay wapas likhein.',
  'Each kind of animal can be on one line only.': 'Har janwar sirf ek line mein likh sakte hain.',
  'This challan has sales, deaths or expenses. Delete those first.':
    'Is challan ki sales, maut ya kharchay likhe hain. Pehle wo mitayein.',
  'There is already a customer with that name.': 'Is naam ka gahak pehle se mojood hai.',
  'There is already a supplier with that name.': 'Is naam ka beopari pehle se mojood hai.',
  "This customer has records, so they can't be deleted.": 'Is gahak ka hisaab likha hai, is liye ye nahi mit sakta.',
  "This supplier has records, so they can't be deleted.": 'Is beopari ka hisaab likha hai, is liye ye nahi mit sakta.',

  // -------------------------------------------- the demo's sample records --
  'Truck from {place}': '{place} se gari',
  'Fell sick in the pen': 'Baaray mein beemar ho gaya',
  'Died on the way from Kohat': 'Kohat se aate hue raste mein mar gaya',
  'Pen rent': 'Baaray ka kiraya',
  'Two helpers': 'Do mazdoor',
}
